# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Sync code signing certificates and provisioning profiles"
  lane :sync_code_signing do
    match(type: "appstore", readonly: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"],
      is_key_content_base64: true,
    )
    match(type: "appstore", readonly: true, api_key: api_key)
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      team_id: ENV["FASTLANE_TEAM_ID"],
      targets: ["Runner"],
      code_sign_identity: "iPhone Distribution",
      profile_name: "match AppStore #{app_id}",
    )
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
      }
    )
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)
  end
end
